---
apiVersion: v1
kind: Service
metadata:
  name: zuulapp
  namespace: default
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8080
      nodePort: 31000
  selector:
    app: zuulapp
