---
apiVersion: v1
kind: Service
metadata:
  name: {{ if index . "serviceName" }}{{.serviceName}}{{else}}{{.appName}}{{end}}
  namespace: {{ if index . "namespace" }}{{.namespace}}{{else}}default{{end}}
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: {{ .serverPort }}
  selector:
    app: {{ if index . "deploymentName" }}{{.deploymentName}}{{else}}{{.appName}}{{end}}